spring:
    application:
        name: EurekaServer

server:
    port: 8761

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8760/eureka/
        register-with-eureka: false
        fetch-registry: false