server:
    port: 8899
    servlet:
        context-path: '/Banamex/API'

spring:
    config:
        import: configserver:http://localhost:8888
    profiles:
        active: development
    application:
        name: TARJETAS_SERVICE





