server:
    port: 8899
    servlet:
        context-path: '/Banamex/API'

spring:
    h2:
        console:
            enabled: 'true'
        datasource:
            url: 'jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false'
            data: 'classpath:schema.sql , classpath:data.sql'
    application:
        name: TARJETAS_SERVICE
    jpa:
        hibernate:
            naming:
                physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
                implicit-strategy: 'org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl'
            ddl-auto: 'update'

management:
    endpoints:
        web:
            exposure:
                include=*:

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost

feign:
    client:
        config:
            default:
                connectTimeout: '5000'
                readTimeout: '5000'