eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
    
feign:
  client:
    config:
      default:
        readTimeout: '5000'
        loggerLevel: FULL
    persons:
      name: PERSONA-SERVICE
      uri: /api/v2/example
      cajeros: /get-cajeros

server:
  port: 9095
  
spring:
  application:
    name: PERSONA-CLIENT