eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'

feign:
  client:
    config:
      default:
        readTimeout: '5000'
        loggerLevel: FULL
    apiCajeros:
      name: API-CAJEROS-SERVICE
      uri: /Cajeros
      cajeros: /get-cajeros

server:
  port: 9095

spring:
  application:
    name: NEAR_ATM_SERVICE
